version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - golang
    networks:
      - backend

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - backend

  golang:
    build:
      context: ./
      dockerfile: Dockerfile.go.config
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
