version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    env_file:
      - variables.env
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/
    depends_on:
      - golang
    networks:
      - backend

  postgres:
    image: postgres:latest
    env_file:
      - variables.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: elestio/pgadmin:latest
    env_file:
      - variables.env
    ports:
      - 8081:80
    depends_on:
      - postgres
    networks:
      - backend

  golang:
    build:
      context: ./
      dockerfile: Dockerfile.go.config
    env_file:
      - variables.env
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
